// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCai_HOS848tz4iKfoeYjjZDnXbE8qoUnI',
    appId: '1:470400475240:web:44b02049124cf358171bdd',
    messagingSenderId: '470400475240',
    projectId: 'mit-oglasi',
    authDomain: 'mit-oglasi.firebaseapp.com',
    storageBucket: 'mit-oglasi.firebasestorage.app',
    measurementId: 'G-2L5CT4Z5L7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6FjL5j5Tr1yHpggxx8_GuLNr0v9AKr7E',
    appId: '1:470400475240:android:ea9ba2479f6e4e8a171bdd',
    messagingSenderId: '470400475240',
    projectId: 'mit-oglasi',
    storageBucket: 'mit-oglasi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBylXPNA0tphGmhSwAAKeS541GvIDuSTSU',
    appId: '1:470400475240:ios:adfc13a16a6798c6171bdd',
    messagingSenderId: '470400475240',
    projectId: 'mit-oglasi',
    storageBucket: 'mit-oglasi.firebasestorage.app',
    iosBundleId: 'com.example.projekatoglasimit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBylXPNA0tphGmhSwAAKeS541GvIDuSTSU',
    appId: '1:470400475240:ios:adfc13a16a6798c6171bdd',
    messagingSenderId: '470400475240',
    projectId: 'mit-oglasi',
    storageBucket: 'mit-oglasi.firebasestorage.app',
    iosBundleId: 'com.example.projekatoglasimit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCai_HOS848tz4iKfoeYjjZDnXbE8qoUnI',
    appId: '1:470400475240:web:76753a46d749f31f171bdd',
    messagingSenderId: '470400475240',
    projectId: 'mit-oglasi',
    authDomain: 'mit-oglasi.firebaseapp.com',
    storageBucket: 'mit-oglasi.firebasestorage.app',
    measurementId: 'G-QTDRNN6QQJ',
  );
}
